Sc value trasnfer tutorial
klaytn/klaytn-docs pull request #388
Opened 2022-03-14 06:30 UTC by hyunsooda

The Value Trasnfer tutorial part in ServiceChain section is entirely re-written, especially focused on execution detail. This PR incorporates five examples (ERC20, ERC21, KIP7, KIP17, and Klay) with an official example repository reference.

2022-03-14 16:08 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
>  - Install `Node.js` (v10.60.0) and `npm` ([How to install](https://nodejs.org/en/download/package-manager/))
Since Node v10 is deprecated, could we use upper versions of node.js?

2022-03-14 16:11 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +- Add rpc option for `subbridge` to `kscnd.conf`. This setting is required for sending rpc call from the deployment script. If you don't need rpc call via script, then it's not necessary.
```suggestion
- Add `subbridge` to `RPC_API` of `kscnd.conf`. This setting is required for sending RPC call from the deployment script.
```

2022-03-14 16:13 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +Perform token deployment with `node erc20-deploy.js` command. This script deploy both bridge contract and token contract and send rpc calls to register and subscribe them.
```suggestion
Perform token deployment by running `node erc20-deploy.js` command. This script deploys both bridge contract and token contract and sends RPC calls to register and subscribe the token contract to the bridge contract.
```

2022-03-14 16:13 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +### Step 3: Token transfer <a id="step-4-token-transfer"></a>
```suggestion
### Step 3: Token transfer <a id="step-3-token-transfer"></a>
```

2022-03-14 16:14 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +You can see the required initialization APIs in the source code. If you want to register manually them, you can type api calls on your attached console.
Could you add a link to "source code"?

2022-03-14 16:15 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +Do not run these commands if you did run `node erc20-deploy.js` since the script already called those APIs and successfully initialized.
```suggestion
Do not run these commands if you did run `node erc20-deploy.js` since the script already called those APIs.
```

Could you check out what happens if we register the same contract twice?

2022-03-14 16:15 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +> subbridge.registerBridge("0x...", "0x...")
```suggestion
> subbridge.registerBridge("0xCHILD_BRIDGE_ADDR", "0xPARENT_BRIDGE_ADDR")
```

2022-03-14 16:16 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
>  ### Step 2: Deploy Contracts <a id="step-2-deploy-contracts"></a>
Does this deploy the bridge contract and token contract as well? Please describe what contracts will be deployed with this.

2022-03-14 16:17 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +The two-step transfer consist of two function calls: (1) approve bridge contract first, and then (2) call contract function(`requestXXXTransfer()`).
Why do we use requestXXX? This is a step-by-step example for ERC-20?

2022-03-15 00:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/klaytn/klaytn-docs?pullRequest=388) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/klaytn/klaytn-docs?pullRequest=388) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/klaytn/klaytn-docs?pullRequest=388) it.</sub>

2022-03-15 08:24 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +KIP7 and KIP17 standards are compatiable token standard with ERC20 and ERC721 standard. We can call `requestERCXXXTransfer()` and `requestKIPXXXTransfer()` functions from KIP7 token contract and ERC
Yes. the additional description is added right after that statement. PTAL.

2022-03-15 08:24 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +- Clone the [cross-chain-transfer-example repository](https://github.com/klaytn/sc-vt).
1. Added [new branch](https://github.com/klaytn/sc-vt/tree/ERC+KLAY). PTAL. I'll change that branch as default when you confirm.
2-1. Re-linked to EN page.
2-2. The configuration file is located in `common` dir.

2022-03-15 08:24 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
>  - Install `Node.js` (v10.60.0) and `npm` ([How to install](https://nodejs.org/en/download/package-manager/))
Updated with a description of recommended is v14.

2022-03-15 08:25 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +The two-step transfer consist of two function calls: (1) approve bridge contract first, and then (2) call contract function(`requestXXXTransfer()`).
Yes.

2022-03-15 08:26 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
>  ### Step 2: Deploy Contracts <a id="step-2-deploy-contracts"></a>
Added additional description.

2022-03-15 08:30 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +You can see the required initialization APIs in the source code. If you want to register manually them, you can type api calls on your attached console.
Just added a word, not specific file location since the corresponding source code are five and seems verbose if the full location is added file by file.

2022-03-15 09:21 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +Do not run these commands if you did run `node erc20-deploy.js` since the script already called those APIs and successfully initialized.
Added implication.

2022-03-15 09:44 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +- Replace `ip` and `port` in the `child` section (SCN node on ServiceChain network) with the actual values of your SCN. The port is RPC_PORT in `kscnd.conf`. The default configuration is using port 7
Good suggestion. Applied. I'll update klaytn-deploy repo soon.

2022-03-15 16:18 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +- Clone the [cross-chain-transfer-example repository](https://github.com/klaytn/sc-vt).
@hyunsooda Good to go! Thanks! No objection to make this as master branch.
But I found something to be fixed.
1. typo "thorugh"
2. KLAY section does not have how to execute. Before execution you should first let readers know that the sender account should have enough KLAY.

2022-03-15 16:21 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +Token contracts are for mint/trasnfer test and bridge contracts are used for the listen/handle value transfer request.
```suggestion
Token contracts are for mint/transfer test and bridge contracts are used for the listen/handle value transfer request.
```

2022-03-15 16:24 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
>  - Replace `key` with the private key of the test account created from [Baobab Wallet](https://baobab.wallet.klaytn.com/) in the previous step
```suggestion
- Replace `key` with the private key of the test account created from [Baobab Wallet](https://baobab.wallet.klaytn.com/) in the previous step.
```

2022-03-15 16:29 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +- Replace `key` with `testkey1` that was generated by `homi`.
```suggestion
- Replace `key` with `testkey1` that was generated by `homi`. Make sure that the corresponding account should have enough KLAY.
```

Hmm?? In your code I cannot find that the KLAY is sent to the bridge contract..?!
https://github.com/klaytn/sc-vt/blob/master/klay/klay-deploy.js

2022-03-15 16:29 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +- Add `subbridge` to `RPC_API` of `kscnd.conf`. This setting is required for sending RPC call from the deployment script.
```suggestion
- Add `subbridge` to `RPC_API` of `kscnd.conf`. This setting is required for sending an RPC call from the deployment script.
```

2022-03-15 16:31 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +> subbridge.subscribeBridge("0x..", "0x...")
Please update this as the above.

2022-03-15 16:31 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +You can see the required initialization APIs in the deployment source code. If you want to register manually them, you can type api calls on your attached console.
```suggestion
You can see the required initialization APIs in the deployment source code. If you want to register manually them, you can type API calls on your attached console.
```

2022-03-15 16:33 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +The two-step transfer consist of two function calls: (1) approve bridge contract first, and then (2) call contract function(`requestXXXTransfer()`).
```suggestion
The two-step transfer consists of two function calls: (1) approve bridge contract first, and then (2) call the contract function(`requestERC20Transfer()`).
```

2022-03-15 16:34 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +## ERC-20 Token Transfer via Compatible Token Contract (two-step) <a id="erc-20-token-transfer-compatiable"></a>
```suggestion
## ERC-20 Token Transfer via Compatible Token Contract (two-step) <a id="erc-20-token-transfer-compatible"></a>
```

2022-03-15 16:36 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +## ERC-20 Token Transfer via Compatible Token Contract (two-step) <a id="erc-20-token-transfer-compatiable"></a>
Hmm... Let's reorg this.

1. Describe ERC-721 examples here. Just explaining how to execute is enough. (1 step and 2 steps together).
2. Make a section. Let's say "KCT (Klaytn Compatible Token) transfer". Then describe that we do not support KIP-7, KIP-17 contracts in the current version, but we can transfer those tokens using ERC-20/721, blabla.

2022-03-16 05:15 UTC, terrikwak commented on docs/node/service-chain/getting-started/value-transfer.md
> +Perform token deployment by running `node erc20-deploy.js` command. This script deploys both bridge contract and token contract and sends RPC calls to register and subscribe the token contract to the
```suggestion
Perform the token deployment by running the command `node erc20-deploy.js`. This script deploys both the bridge contract and the token contract, and sends RPC calls to register and subscribe the token contract to the bridge contract.
```

2022-03-16 05:15 UTC, terrikwak commented on docs/node/service-chain/getting-started/value-transfer.md
> +Do not run these commands if you did run `node erc20-deploy.js` since the script already called those APIs (It cause duplicated error).
```suggestion
Do not run these commands if you ran `node erc20-deploy.js` since the script already called those APIs (It causes a duplicate error).
```

2022-03-16 05:15 UTC, terrikwak commented on docs/node/service-chain/getting-started/value-transfer.md
> +Perform token transfer with `node erc20-transfer-1step.js` command.
```suggestion
Perform token transfer with the command `node erc20-transfer-1step.js`.
```

2022-03-16 05:15 UTC, terrikwak commented on docs/node/service-chain/getting-started/value-transfer.md
> +Run erc20-transfer-2step.js for two-step transfer example.
```suggestion
Run erc20-transfer-2step.js for the two-step transfer example.
```

2022-03-16 05:15 UTC, terrikwak commented on docs/node/service-chain/getting-started/value-transfer.md
> +KIP7 and KIP17 standards are compatiable token standard with ERC20 and ERC721 standard. We can call `requestERCXXXTransfer()` and `requestKIPXXXTransfer()` functions from KIP7 token contract and ERC
```suggestion
KIP7 and KIP17 are compatiable with the token standards ERC20 and ERC721. We can call `requestERCXXXTransfer()` and `requestKIPXXXTransfer()` functions from the KIP7 token contract and the ERC token contract, respectively.
```

2022-03-16 05:15 UTC, terrikwak commented on docs/node/service-chain/getting-started/value-transfer.md
> +Currently, the bridge contract, provided by Klaytn team supports only `requestERC20Transfer()` and `requestERC721Transfer()` for token trasnfer. The corresponding request functions for KIP7 and KIP17
```suggestion
Currently, the bridge contract provided by the Klaytn team supports only `requestERC20Transfer()` and `requestERC721Transfer()` for token trasnfer. The corresponding request functions for KIP7 and KIP17 will be supported soon.
```

2022-03-16 05:15 UTC, terrikwak commented on docs/node/service-chain/getting-started/value-transfer.md
> +The below command shows example of seding KIP7 token using ERC20 interface with `requestERC20Transfer()`.
```suggestion
The below command is an example of sending KIP7 tokens using the ERC20 interface with `requestERC20Transfer()`.
```

2022-03-16 05:15 UTC, terrikwak commented on docs/node/service-chain/getting-started/value-transfer.md
> +The workflow is same as above. `erc721`, `kip7`, `kip17`, and `klay` directories contain corresponding example source code.
```suggestion
The workflow is the same as above. `erc721`, `kip7`, `kip17`, and `klay` directories contain corresponding example source code.
```

2022-03-16 13:13 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +- Clone the [cross-chain-transfer-example repository](https://github.com/klaytn/sc-vt).
1. Fixed.
2. Added a balance check caution.

2022-03-16 13:15 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +- Replace `key` with `testkey1` that was generated by `homi`.
[PTAL again](https://github.com/klaytn/sc-vt/tree/master/klay).

2022-03-16 13:23 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +> subbridge.subscribeBridge("0x..", "0x...")
Updated.

2022-03-16 13:29 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +## ERC-20 Token Transfer via Compatible Token Contract (two-step) <a id="erc-20-token-transfer-compatiable"></a>
1. The execution detail is already explained in the example repository. Do you think need it twice here still?
2. The same case as above.

Then, what about (1) bringing them here or (2) writing twice here?

2022-03-17 08:37 UTC, terrikwak commented on docs/node/service-chain/getting-started/value-transfer.md
>  This section will explain how to enable ERC-20 value transfer between Baobab network and your service chain with the provided test code.
```suggestion
This section will explain how to enable ERC-20 value transfer between Baobab network and your ServiceChain with the provided test code.
```

2022-03-17 08:37 UTC, terrikwak commented on docs/node/service-chain/getting-started/value-transfer.md
>  - We assume that you installed the service chain, and connected the service chain to the Baobab EN ([link](en-scn-connection.md)).
```suggestion
- We assume that you installed the ServiceChain, and connected the ServiceChain to the Baobab EN ([link](en-scn-connection.md)).
```

2022-03-17 08:38 UTC, terrikwak commented on docs/node/service-chain/getting-started/value-transfer.md
> +In this step, we would deploy both bridge contract and token contract in parent chain as well as child chain.
```suggestion
In this step, we would deploy both the bridge contract and token contract in the parent as well as the child chain.
```

2022-03-17 08:39 UTC, terrikwak commented on docs/node/service-chain/getting-started/value-transfer.md
> +Token contracts are for mint/transfer test and bridge contracts are used for the listen/handle value transfer request.
```suggestion
Token contracts are for mint/transfer test and bridge contracts are used to listen/handle value transfer requests.
```

2022-03-18 04:31 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +$ node erc20-transfer-2step.js
Isn't it print some logs? If then please add them here so that readers understand they executed well.

2022-03-18 04:34 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +## ERC-20 Token Transfer via Compatible Token Contract (two-step) <a id="erc-20-token-transfer-compatiable"></a>
Let me make clear on this.
1. "ERC-20 Token Transfer via Compatible Token Contract" seems not aligned in the description. The description explains "KCT(KIP-7 and KIP-17)s Token Transfer via ERC-20 and ERC-721 interface".
2. Instead of providing general information, let's say here to "KIP-7 Token Transfer via ERC-20 Interface".
3. then, in the next section, other value transfers are described in this repo. blabla.

2022-03-18 05:13 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +$ node erc20-transfer-2step.js
Thanks, added.

2022-03-18 05:13 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +## ERC-20 Token Transfer via Compatible Token Contract (two-step) <a id="erc-20-token-transfer-compatiable"></a>
Revised. PTAL.

2022-03-18 05:55 UTC, henry-will requested changes

2022-03-18 05:55 UTC, henry-will commented on docs/node/service-chain/getting-started/value-transfer.md
> +- Clone the [cross-chain-transfer-example repository](https://github.com/klaytn/sc-vt).
I cann't match cross-chain-transer-example and sc-vt repo name.
Can you change sc-vt to servicechain-value-transfer-examples

2022-03-18 06:17 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +- Clone the [cross-chain-transfer-example repository](https://github.com/klaytn/sc-vt).
Thanks. resolved.

2022-03-18 15:19 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
>  Check if the result is `alice balance: 100`.
```suggestion
If the result is `alice balance: 100`, then it has been executed successfully.
```

2022-03-18 15:20 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +The two-step transfer consists of two function calls: (1) approve bridge contract first, and then (2) call the contract function(`requestERC20Transfer()`).
```suggestion
The two-step transfer consists of two function calls: (1) approve the bridge contract first, and then (2) call the contract function `requestERC20Transfer()`.
```

2022-03-18 15:23 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +KIP7 is compatiable token standard with ERC20. We can call `requestERC20Transfer()` function from the KIP7 token contract and vice versa.
```suggestion
KIP-7 is a compatible token standard with ERC20. We can call `requestERC20Transfer()` function to a KIP-7 token contract to transfer KIP-7 Tokens between a parent chain and a child chain.
```

2022-03-18 15:25 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +In the case of sending the KIP-7 token via ERC20 interface, we call the `approve()` function to allow the bridge can send the token instaed of the transaction sender, and then call the `requestERC20T
```suggestion
In the case of sending KIP-7 tokens via ERC-20 interface, we call the `approve()` function to allow the bridge to send the tokens on behalf of the transaction sender. Then call the `requestERC20Transfer()` function.
```

2022-03-18 15:25 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +The below command is an example of sending KIP7 tokens using the ERC20 interface with `requestERC20Transfer()`.
```suggestion
The below command is an example of sending KIP-7 tokens using the ERC-20 interface with `requestERC20Transfer()`.
```

2022-03-18 15:26 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +$ node kip7-deploy.js
Don't we have deployment for ERC-20? Why do we have this?

2022-03-18 15:29 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +## To Be Supported
```suggestion
## Native Support for KIP-7 and KIP-17 (To Be Implemented)
```

2022-03-18 15:29 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +Currently, the bridge contract provided by the Klaytn team supports only `requestERC20Transfer()` and `requestERC721Transfer()` for token trasnfer. The corresponding request functions for KIP7 and KI
```suggestion
Currently, the bridge contract provided by the Klaytn team supports only `requestERC20Transfer()` and `requestERC721Transfer()` for token transfer. The corresponding request functions for KIP-7 and KIP-17 will be supported soon.
```

2022-03-18 15:30 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +## ERC-721, KIP7, KIP17, KLAY Transfer <a id="erc-721-token-transfer"></a>
```suggestion
## Value Transfer for ERC-721, KIP17, and KLAY <a id="value-transfer-for-erc-721-kip17-and-klay"></a>
```

2022-03-18 15:32 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +The workflow is the same as above. `erc721`, `kip7`, `kip17`, and `klay` directories contain corresponding example source code.
```suggestion
The workflow is the same as above. [`erc721`](https://github.com/klaytn/servicechain-value-transfer-examples/tree/master/erc721), [`kip17`](https://github.com/klaytn/servicechain-value-transfer-examples/tree/master/kip17), and [`klay`](https://github.com/klaytn/servicechain-value-transfer-examples/tree/master/klay) directories contain corresponding example source code.
```

2022-03-19 14:18 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +$ node kip7-deploy.js
I couldn't understand what you points out. The example is sending KIP-7 token via the ERC-20 interface. That's why the example deploys the KIP-7 token. Is it what you concerned? The example that deploys ERC-20 appeared above.

2022-03-20 14:30 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +## KIP-7 Token Transfer via ERC-20 Interface (two-step) <a id="erc-20-token-transfer-compatiable"></a>
```suggestion
## KIP-7 Token Transfer via ERC-20 Interface (two-step) <a id="kip-7-token-transfer-via-erc-20-interface-two-step"></a>
```

2022-03-20 14:33 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +$ node kip7-deploy.js
Sorry. I missed some contexts.

In the previous examples, we have three '##' headings:
```
## ERC-20 Token Transfer (one-step) <a id="erc-20-token-transfer-onestep"></a>
## ERC-20 Token Transfer (two-step) <a id="erc-20-token-transfer-twostep"></a>
## KIP-7 Token Transfer via ERC-20 Interface (two-step) <a id="erc-20-token-transfer-compatiable"></a>
```
Only second one does not introduce 'ERC-20 deployment'. At least you have to mention how to deploy that or it has to have 'already deployed in the previous section' or something similar.

2022-03-21 00:18 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +$ node kip7-deploy.js
Added.

2022-03-21 23:28 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +We do not deploy contracts since we already deployed both birdge and token contracts. You must deploy first if you didn't deploy them.
```suggestion
We do not deploy contracts since we already deployed both bridge and token contracts. You must deploy first if you didn't deploy them. You can deploy the contract using `node erc20-deploy.js`.
```

2022-03-21 23:29 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +```
```suggestion
The below command is an example of sending KIP-7 tokens using the ERC-20 interface with `requestERC20Transfer()`.
```
```

2022-03-21 23:29 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +
```suggestion
The below command is an example of sending KIP-7 tokens using the ERC-20 interface with `requestERC20Transfer()`.

```

2022-03-21 23:31 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +The below command is an example of sending KIP-7 tokens using the ERC-20 interface with `requestERC20Transfer()`.
```suggestion
The below command deploys the bridge contract and a KIP-7 contract. Then it registers and subscribes the bridge contract.
```

2022-03-21 23:33 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +Currently, the bridge contract provided by the Klaytn team supports only `requestERC20Transfer()` and `requestERC721Transfer()` for token transfer. The corresponding request functions for KIP-7 and K
```suggestion
Currently, the bridge contract provided by the Klaytn team supports only `requestERC20Transfer()` and `requestERC721Transfer()` for token transfer. The corresponding request functions for KIP-7 and KIP-17 will be supported soon. Before the implementation is done, as you can see above, you can transfer KIP-7 tokens using ERC-20 interfaces.
```

2022-03-22 15:22 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +- We assume that you installed the ServiceChain, and connected the ServiceChain to the Baobab EN ([link](en-scn-connection.md)).
```suggestion
- We assume that you installed the ServiceChain, and connected the ServiceChain to the Baobab EN by the instructions in [Connecting to Baobab](en-scn-connection.md).
```

2022-03-22 15:23 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +- Clone the [cross-chain-transfer-example repository](https://github.com/klaytn/servicechain-value-transfer-examples).
```suggestion
- Clone the repository [servicechain-value-transfer-examples](https://github.com/klaytn/servicechain-value-transfer-examples).
```

2022-03-22 15:24 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +- Clone the [cross-chain-transfer-example repository](https://github.com/klaytn/servicechain-value-transfer-examples).
```suggestion
Clone the repository [servicechain-value-transfer-examples](https://github.com/klaytn/servicechain-value-transfer-examples).
```

2022-03-22 15:28 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +- Replace `key` with the private key of the test account created from [Baobab Wallet](https://baobab.wallet.klaytn.com/) in the previous step.
```suggestion
- Replace `parent.key` with the private key of the test account created from [Baobab Wallet](https://baobab.wallet.klaytn.com/) in the previous step.
```

2022-03-22 15:29 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +Perform the token deployment by running the command `node erc20-deploy.js`. This script deploys both the bridge contract and the token contract, and sends RPC calls to register and subscribe the toke
```suggestion
Perform the token deployment by running the command `node erc20-deploy.js`. This script deploys both the bridge contract and the token contract, and it sends RPC calls to register and subscribe the token contract to the bridge contract.
```

2022-03-22 15:31 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
>  ```
Do we need this one actually? I think we can remove this section because the readers can actually run this command without reading these sentences.

2022-03-22 15:34 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +Perform token transfer with the command `node erc20-transfer-1step.js`.
```suggestion
Perform token transfer with the command `node erc20-transfer-1step.js`. This one-step token transfer requires modification of an ERC-20 token implementation. If you don't want to modify the token contract or you have a token contract that is already deployed, please refer to [ERC-20 Token Transfer (two-step)](erc-20-token-transfer-twostep).
```

2022-03-22 15:36 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +Run erc20-transfer-2step.js for the two-step transfer example.
```suggestion
Run erc20-transfer-2step.js for the two-step transfer example. With this two-step token transfer example, unmodified ERC-20 token contracts can be used.
```

2022-03-22 15:37 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +We do not deploy contracts since we already deployed both bridge and token contracts. You must deploy first if you didn't deploy them. You can deploy the contract using `node erc20-deploy.js`.
```suggestion
We do not deploy contracts in this section since we already deployed both bridge and token contracts. You must deploy first if you didn't deploy them. You can deploy the contract using `node erc20-deploy.js`.
```

2022-03-22 15:38 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +KIP-7 is a compatible token standard with ERC20. We can call `requestERC20Transfer()` function to a KIP-7 token contract to transfer KIP-7 Tokens between a parent chain and a child chain.
```suggestion
[KIP-7](https://kips.klaytn.com/KIPs/kip-7) is a token standard compatible with ERC-20. We can call `requestERC20Transfer()` function to a KIP-7 token contract to transfer KIP-7 tokens between a parent chain and a child chain.
```

2022-03-22 15:38 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +In the case of sending KIP-7 tokens via ERC-20 interface, we call the `approve()` function to allow the bridge to send the tokens on behalf of the transaction sender. Then call the `requestERC20Trans
```suggestion
In the case of sending KIP-7 tokens via the ERC-20 interface, we call the `approve()` function to allow the bridge to send the tokens on behalf of the transaction sender. Then call the `requestERC20Transfer()` function.
```

2022-03-22 15:39 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +The workflow is the same as above. [`erc721`](https://github.com/klaytn/servicechain-value-transfer-examples/tree/master/erc721), [`kip17`](https://github.com/klaytn/servicechain-value-transfer-examp
```suggestion
The workflow for ERC-721, KIP-17 and KLAY is the same as above. [`erc721`](https://github.com/klaytn/servicechain-value-transfer-examples/tree/master/erc721), [`kip17`](https://github.com/klaytn/servicechain-value-transfer-examples/tree/master/kip17), and [`klay`](https://github.com/klaytn/servicechain-value-transfer-examples/tree/master/klay) directories contain corresponding example source code.
```

2022-03-23 08:59 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
>  ```
Uhm, I thought it would be helpful to give this instruction since these are actually required steps. These steps are currently implicitly behind of scenes due to the RPC request in the example code. So I've written explicitly.

2022-03-23 09:03 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +$ node erc20-deploy.js
Added.

2022-03-23 09:05 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +Perform token transfer with the command `node erc20-transfer-1step.js`.
Thank you. Good suggestion.

2022-03-23 09:08 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +The workflow is the same as above. [`erc721`](https://github.com/klaytn/servicechain-value-transfer-examples/tree/master/erc721), [`kip17`](https://github.com/klaytn/servicechain-value-transfer-examp
Added KIP7 once committed this suggestion

2022-03-23 15:31 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
>  ```
Okay, I'm also good with this explicit execution, but we need to somehow make the readers not execute this. Any good idea?

2022-03-23 15:33 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +The workflow is the same as above. [`erc721`](https://github.com/klaytn/servicechain-value-transfer-examples/tree/master/erc721), [`kip17`](https://github.com/klaytn/servicechain-value-transfer-examp
@hyunsooda Do we need to add KIP7?
1. Please use "KIP-7" if we refer to the token standard.
2. KIP-7 is already described previously, I think. Do we need this one here? Then, we also provide a link for KIP-7 like others.

2022-03-25 09:03 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
>  ```
I've already written `Do not run these commands ...` Do you think this warning is insufficient?

2022-03-25 09:04 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +The workflow is the same as above. [`erc721`](https://github.com/klaytn/servicechain-value-transfer-examples/tree/master/erc721), [`kip17`](https://github.com/klaytn/servicechain-value-transfer-examp
Uh oh, I'm sorry. I forgot that I'd described it. You seem to be more aware of this tutorial than I, even though I'm the author of this draft. Thanks. 

Let me have a caution for the correct word. Thanks.

2022-03-25 16:44 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
>  ```
Ah, okay, then let't more emphasize that.

2022-03-25 16:44 UTC, kjhman21 commented on docs/node/service-chain/getting-started/value-transfer.md
> +Do not run these commands if you ran `node erc20-deploy.js` since the script already called those APIs (It causes a duplicate error).
```suggestion
NOTE: DO NOT run these commands if you ran `node erc20-deploy.js` since the script already called those APIs (It causes a duplicate error).
```

2022-03-28 10:26 UTC, kjhman21 commented
@hyunsooda Thanks for the hard work! I'm done!

@terrikwak @henry-will Could you review this again?

2022-03-29 11:23 UTC, henry-will approved these changes

2022-03-29 11:23 UTC, henry-will commented on docs/node/service-chain/getting-started/value-transfer.md
> +> ------------------------- erc20-transfer-2step START -------------------------
">" some one is used, some one is not used.

2022-03-31 14:54 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +------------------------- erc20-deploy END -------------------------
That's the actual output. It seems good to keep it as it is so that users following this tutorial can feel everything is executed well exactly with the tutorial's output.

2022-03-31 14:54 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +info.bridge: 0xcb9e197cc328c39376C5aB7Dc5d3C684D5F9d2f3
It's described [here](https://github.com/klaytn/klaytn-docs/pull/388/files#diff-334f69598a39791db11b9f36a46212ee4c3d4f5e96164a93fd0b20e50b3d5df5R110)

2022-03-31 14:56 UTC, hyunsooda commented on docs/node/service-chain/getting-started/value-transfer.md
> +> ------------------------- erc20-transfer-2step START -------------------------
Thanks. Removed all.

2022-04-01 05:30 UTC, henry-will commented on docs/node/service-chain/getting-started/value-transfer.md
> +         "url": "http://192.168.0.5:8551",
Okay, I mistook about that environment. Thank you for your answer.

2022-04-01 05:31 UTC, henry-will approved these changes

2022-04-01 08:16 UTC, terrikwak approved these changes

2022-04-04 06:37 UTC, kjhman21 approved these changes

2022-04-07 04:13 UTC, merged