Gas pages refactoring
klaytn/klaytn-docs pull request #518
Opened 2022-12-08 15:13 UTC by yoomee1313

## Proposed changes

- 1. Refactoring gas pages: Transaction fees, Klaytn virtual machine
- 2. Apply Kore hardfork change, and most of the changes are about the gas

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Minor Issues and Typos
- [ ] Major Content Contribution
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to reach out. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [ ] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn-docs/blob/master/CONTRIBUTING.md)
- [ ] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn-docs)
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large content contribution, kick off the discussion by explaining why you would suggest the content contribution, etc...

2022-12-09 05:44 UTC, henry-will requested changes

2022-12-09 05:44 UTC, henry-will commented on docs/klaytn/design/computation/computation-cost/computation-cost.md
> +NOTE: This document is written based on the latest EVM which have been used since the `Kore` hardfork.
It's hard to understand which one you want to explain after Kore. If this section explains about computation cost basis of the latest EVM opcodes, adding the target object seems good. 
```suggestion
NOTE: This document(chapter or section) explains(or discusses) about computation cost basis of the latest EVM opcodes which have been used since the `Kore` hardfork.
```

2022-12-09 05:44 UTC, henry-will commented on docs/klaytn/design/computation/computation-cost/computation-cost.md
> +`Kore` hardfork block number is as follows.
```suggestion
`Kore` hardfork block numbers are as follows.
```

2022-12-09 05:44 UTC, henry-will commented on docs/klaytn/design/computation/execution-model.md
> +A smart contract can be created in the Klaytn blockchain by sending a transaction to an empty address with the binary as data. The binary can be in various formats; however, Klaytn currently supports
How about adding a eip3541 link.
[eip-3541](https://eips.ethereum.org/EIPS/eip-3541)

2022-12-13 01:30 UTC, yoomee1313 commented on docs/klaytn/design/computation/computation-cost/computation-cost.md
> +NOTE: This document is written based on the latest EVM which have been used since the `Kore` hardfork.
Good point. What about this? Reading it again, it seems that there is no need to talk about EVM..
```
NOTE: Computation costs have changed with the `Kore` hardfork.
```

2022-12-14 04:31 UTC, yoomee1313 commented on docs/klaytn/design/computation/execution-model.md
> +A smart contract can be created in the Klaytn blockchain by sending a transaction to an empty address with the binary as data. The binary can be in various formats; however, Klaytn currently supports
added at https://github.com/klaytn/klaytn-docs/pull/518/commits/242924c1aadf1a43e3223a44098c54e5e9edbe2b

2022-12-14 04:42 UTC, yoomee1313 commented on docs/klaytn/design/computation/computation-cost/computation-cost.md
> +NOTE: This document is written based on the latest EVM which have been used since the `Kore` hardfork.
changed at https://github.com/klaytn/klaytn-docs/pull/518/commits/06f6a658ce86ba316298436e84c23393a0855b03

2022-12-27 07:40 UTC, jiwon-lieb commented on docs/klaytn/design/computation/computation-cost/computation-cost.md
> +* Baobab Testnet: please refer [this](https://github.com/klaytn/klaytn/blob/b01f8f3b7aa69afc1f7693e652adc5f2d8fa4ab6/params/config.go#L79)
```suggestion
* Baobab Testnet: please refer to this [link](https://github.com/klaytn/klaytn/blob/b01f8f3b7aa69afc1f7693e652adc5f2d8fa4ab6/params/config.go#L79)
```

2022-12-27 07:41 UTC, jiwon-lieb commented on docs/klaytn/design/computation/computation-cost/computation-cost.md
> +* Cypress Mainnet: please refer [this](https://github.com/klaytn/klaytn/blob/b01f8f3b7aa69afc1f7693e652adc5f2d8fa4ab6/params/config.go#L49)
```suggestion
* Cypress Mainnet: please refer to this [link](https://github.com/klaytn/klaytn/blob/b01f8f3b7aa69afc1f7693e652adc5f2d8fa4ab6/params/config.go#L49)
```

2022-12-27 07:41 UTC, jiwon-lieb commented on docs/klaytn/design/computation/computation-cost/computation-cost.md
> +* Cypress Mainnet: please refer [this](https://github.com/klaytn/klaytn/blob/b01f8f3b7aa69afc1f7693e652adc5f2d8fa4ab6/params/config.go#L49)
```suggestion
* Cypress Mainnet: please refer to this [link](https://github.com/klaytn/klaytn/blob/b01f8f3b7aa69afc1f7693e652adc5f2d8fa4ab6/params/config.go#L49)
```

2022-12-27 07:42 UTC, jiwon-lieb commented on docs/klaytn/design/computation/computation-cost/computation-cost.md
> +* Cypress Mainnet: please refer [this](https://github.com/klaytn/klaytn/blob/b01f8f3b7aa69afc1f7693e652adc5f2d8fa4ab6/params/config.go#L49)
```suggestion
* Cypress Mainnet: please refer to this [link](https://github.com/klaytn/klaytn/blob/b01f8f3b7aa69afc1f7693e652adc5f2d8fa4ab6/params/config.go#L49)
```

2022-12-27 07:42 UTC, jiwon-lieb commented on docs/klaytn/design/computation/computation-cost/computation-cost.md
> +* Cypress Mainnet: please refer [this](https://github.com/klaytn/klaytn/blob/b01f8f3b7aa69afc1f7693e652adc5f2d8fa4ab6/params/config.go#L49)
```suggestion
* Cypress Mainnet: please refer to this [link](https://github.com/klaytn/klaytn/blob/b01f8f3b7aa69afc1f7693e652adc5f2d8fa4ab6/params/config.go#L49)
```

2022-12-27 07:44 UTC, jiwon-lieb commented on docs/klaytn/design/computation/klaytn-virtual-machine/klaytn-virtual-machine-previous.md
> +Fees \(denominated in gas\) are charged under three distinct circumstances. Sometimes, some policies may be omitted.
may be omitted 한국어 원문이 어떤 뜻인가요?

2022-12-27 07:45 UTC, jiwon-lieb commented on docs/klaytn/design/computation/klaytn-virtual-machine/klaytn-virtual-machine-previous.md
> +The fee schedule `G` is a tuple of 36 scalar values corresponding to the relative costs, in gas, of a number of abstract operations that a transaction may incur. Also, there's gas items to calculate
이거 한국어 원문 좀 보여주실 수 있을까요?

2022-12-27 07:47 UTC, jiwon-lieb commented on docs/klaytn/design/computation/klaytn-virtual-machine/klaytn-virtual-machine-previous.md
> +Here, I will briefly explain the gas calculation logic during contract execution using the fee schedule variables defined above. As this explanation assumes a general situation, the unusual situation
```suggestion
Below is a brief explanation of the gas calculation logic during contract execution using the fee schedule variables defined above. As it assumes a general situation, unusual situations such as revert appears is not considered.
```

2023-01-02 06:08 UTC, yoomee1313 commented on docs/klaytn/design/computation/klaytn-virtual-machine/klaytn-virtual-machine-previous.md
> +Fees \(denominated in gas\) are charged under three distinct circumstances. Sometimes, some policies may be omitted.
`몇몇 정책들은 가끔씩 생략될 수 있다.` 입니다.

2023-01-02 06:16 UTC, yoomee1313 commented on docs/klaytn/design/computation/klaytn-virtual-machine/klaytn-virtual-machine-previous.md
> +The fee schedule `G` is a tuple of 36 scalar values corresponding to the relative costs, in gas, of a number of abstract operations that a transaction may incur. Also, there's gas items to calculate
> The fee schedule `G` is a tuple of 36 scalar values corresponding to the relative costs, in gas, of a number of abstract operations that a transaction may incur.
> 비용표 G는 트랜잭션에서 발생할 수 있는 연산의 가스값 정보를 가지고 있는 37개 스칼라값을 가진 튜플(tuple)입니다. 
요 내용의 출처는 여기입니다. https://ko.docs.klaytn.foundation/content/klaytn/design/computation/klaytn-virtual-machine#fee-schedule

> Also, there's gas items to calculate the gas of the precompiled contracts called by `CALL_*` opcodes.
이 줄은 이번에 제가 추가한건데요, `CALL_* opcode들로부터 호출되는 precompiled contracts의 가스를 계산하는데에 쓰이는 가스 아이템들도 있다.` 라는 뜻입니다.

2023-01-02 06:17 UTC, yoomee1313 commented on docs/klaytn/design/computation/computation-cost/computation-cost.md
> +* Baobab Testnet: please refer [this](https://github.com/klaytn/klaytn/blob/b01f8f3b7aa69afc1f7693e652adc5f2d8fa4ab6/params/config.go#L79)
reflected at https://github.com/klaytn/klaytn-docs/pull/518/commits/a11e18981c19918f07a0639d51894aaf45987c61

2023-01-02 06:19 UTC, yoomee1313 commented on docs/klaytn/design/computation/computation-cost/computation-cost.md
> +* Cypress Mainnet: please refer [this](https://github.com/klaytn/klaytn/blob/b01f8f3b7aa69afc1f7693e652adc5f2d8fa4ab6/params/config.go#L49)
reflected at https://github.com/klaytn/klaytn-docs/commit/a11e18981c19918f07a0639d51894aaf45987c61

2023-01-02 06:19 UTC, yoomee1313 commented on docs/klaytn/design/computation/computation-cost/computation-cost.md
> +* Cypress Mainnet: please refer [this](https://github.com/klaytn/klaytn/blob/b01f8f3b7aa69afc1f7693e652adc5f2d8fa4ab6/params/config.go#L49)
reflected at https://github.com/klaytn/klaytn-docs/commit/a11e18981c19918f07a0639d51894aaf45987c61

2023-01-02 06:19 UTC, yoomee1313 commented on docs/klaytn/design/computation/computation-cost/computation-cost.md
> +* Cypress Mainnet: please refer [this](https://github.com/klaytn/klaytn/blob/b01f8f3b7aa69afc1f7693e652adc5f2d8fa4ab6/params/config.go#L49)
reflected at https://github.com/klaytn/klaytn-docs/commit/a11e18981c19918f07a0639d51894aaf45987c61

2023-01-02 06:19 UTC, yoomee1313 commented on docs/klaytn/design/computation/computation-cost/computation-cost.md
> +* Cypress Mainnet: please refer [this](https://github.com/klaytn/klaytn/blob/b01f8f3b7aa69afc1f7693e652adc5f2d8fa4ab6/params/config.go#L49)
reflected at https://github.com/klaytn/klaytn-docs/commit/a11e18981c19918f07a0639d51894aaf45987c61

2023-01-02 06:23 UTC, yoomee1313 commented on docs/klaytn/design/computation/klaytn-virtual-machine/klaytn-virtual-machine-previous.md
> +Fees \(denominated in gas\) are charged under three distinct circumstances. Sometimes, some policies may be omitted.
`some policies are ignored.` 가 더 자연스러울까요?

2023-03-29 05:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/klaytn/klaytn-docs?pullRequest=518) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/klaytn/klaytn-docs?pullRequest=518) before we can accept your contribution.<br/><hr/>**yumiel.ko** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/klaytn/klaytn-docs?pullRequest=518) it.</sub>

2023-04-21 03:30 UTC, aidan-kwon commented
@yoomee1313 Please resolve conflicts

2023-04-24 05:38 UTC, aidan-kwon commented on docs/klaytn/design/computation/klaytn-virtual-machine/klaytn-virtual-machine-previous.md
> +Fees \(denominated in gas\) are charged under three distinct circumstances. Sometimes, some policies may be omitted.
아래 내용에 대해서죠? 어차피 Second, final 문장에 "may" 로 적혀있기 때문에 굳이 "Sometimes, some policies may be omitted." 써서 헷갈리게 할 필요가 있나 싶어요

2023-04-24 05:58 UTC, aidan-kwon commented on docs/klaytn/design/computation/klaytn-virtual-machine/klaytn-virtual-machine-previous.md
> +| 0x11 | validateSender | ValidateSenderGas | 5000 |
These addresses are changed to 0x3fd ~ 0x3ff

2023-04-24 05:59 UTC, aidan-kwon commented on docs/klaytn/design/computation/klaytn-virtual-machine/klaytn-virtual-machine-previous.md
> +| 0x11 | validateSender | ValidateSenderGas | 5000 |
And, new pre-compiled contracts are introduced

2023-04-24 06:09 UTC, yoomee1313 commented on docs/klaytn/design/computation/klaytn-virtual-machine/klaytn-virtual-machine-previous.md
> +Fees \(denominated in gas\) are charged under three distinct circumstances. Sometimes, some policies may be omitted.
네 지웠습니다

2023-04-24 06:18 UTC, yoomee1313 commented on docs/klaytn/design/computation/klaytn-virtual-machine/klaytn-virtual-machine-previous.md
> +| 0x11 | validateSender | ValidateSenderGas | 5000 |
This page contains the klvm information used before the activation of hardforks.

2023-04-24 06:33 UTC, yoomee1313 commented on docs/klaytn/design/computation/klaytn-virtual-machine/klaytn-virtual-machine-previous.md
> +| 0x11 | validateSender | ValidateSenderGas | 5000 |
Btw, I think this previous page is confusing. This page was added because there was only istanbulCompatible hf at that time, but it's not effective anymore.

I'll delete this page and add the descriptions about the changes at each page like this later.
```
0x09 | blake2b(before istanbulHf, it was vmLog) |
``` 

For now, please ignore this pages.

2023-04-24 07:40 UTC, aidan-kwon commented on docs/klaytn/design/transaction-fees/transaction-fees.md
> +| AccountCreation | TxGas | O | X |
We don't have AccountCreation type. The implementation has never been enabled.

2023-04-27 16:34 UTC, kjhman21 commented on docs/klaytn/design/computation/computation-cost/computation-cost.md
> +NOTE: Computation costs have changed with the `Kore` hardfork. If you want the previous document, please refer to [previous document](computation-cost-previous.md).
Don't we also need to update computation-cost-previous.md?

2023-04-28 06:38 UTC, yoomee1313 commented on docs/klaytn/design/computation/computation-cost/computation-cost.md
> +NOTE: Computation costs have changed with the `Kore` hardfork. If you want the previous document, please refer to [previous document](computation-cost-previous.md).
the previous page contains the initial vm. 

However, as mentioned in https://github.com/klaytn/klaytn-docs/pull/518#discussion_r1174840828, i'm going to replace those pages to a one summary page or add the descriptions about the changes at each page later.

2023-07-10 06:04 UTC, yoomee1313 commented
I apologize for not paying attention since it's been delayed a lot.
@Colin (Dev) @ayo-klaytn Could you approve this PR? As it is delayed a lot, it would be better to update the grammar or style-related content in other PR.

2023-07-10 06:36 UTC, ayo-klaytn approved these changes

2023-07-11 23:39 UTC, kjhman21 approved these changes

2023-07-11 23:40 UTC, kjhman21 commented
@yoomee1313 So, you mean, you need to update more in this PR? or you will do it later in another PR?

2023-07-12 02:10 UTC, yoomee1313 commented
@kjhman21 I need to update some more, and I'll do it in other PR :)

2023-07-12 04:39 UTC, kjhman21 commented
@yoomee1313 Okay, then I will merge this as it is. would it be okay?

2023-07-12 05:15 UTC, yoomee1313 commented
@kjhman21 Yes, please do so.

2023-07-12 05:36 UTC, merged