New Crowdin updates
klaytn/klaytn-docs pull request #657
Opened 2024-01-12 09:40 UTC by klaytndocs

2024-01-12 10:12 UTC, ayo-klaytn approved these changes

2024-01-15 07:56 UTC, ayo-klaytn commented on i18n/vi/code.json
>      "message": "{tagline}"
@scott-klaytn The content in the VI folder seems to have reverted back to EN, compared to the KO folder that is well translated in the native language. Can you look into this?

2024-01-15 08:09 UTC, scott-klaytn commented on i18n/vi/code.json
>      "message": "{tagline}"
It's normal that it shows the EN strings instead of localized strings until I upload the JSON translation files to Crowdin again (I'm working on it). That's the way how Crowdin works when integrated with Github. Anyway, the reverted Strings will not appear on the site unless it's approved. I'll let you know when to approve this automatic PR from Crowdin.

2024-01-15 08:12 UTC, ayo-klaytn commented on i18n/vi/code.json
>      "message": "{tagline}"
Got it. Thanks

2024-01-15 08:12 UTC, scott-klaytn requested changes
Need to be held until uploading and syncing translation are completed in Crowdin.

2024-02-23 06:43 UTC, scott-klaytn approved these changes

2024-02-23 06:44 UTC, merged